### ISSUE TITLE
EF 7

### ISSUE THREAD

**Issue by yltsa** [Rwing/EntityFrameworkCore.UseRowNumberForPaging#8]
Hi,

I updated my ASP.NET Core MVC application to .NET 7.0. But cannot upgrade Entity Framework from 6.0 to 7.0 because this module causes an error with EF7. EF6 is OK.

Error message with EF7:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.Update(System.Collections.Generic.IReadOnlyList`1<Microsoft.EntityFrameworkCore.Query.SqlExpressions.ProjectionExpression>, System.Collections.Generic.IReadOnlyList`1<Microsoft.EntityFrameworkCore.Query.SqlExpressions.TableExpressionBase>, Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlExpression, System.Collections.Generic.IReadOnlyList`1<Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlExpression>, Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlExpression, System.Collections.Generic.IReadOnlyList`1<Microsoft.EntityFrameworkCore.Query.SqlExpressions.OrderingExpression>, Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlExpression, Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlExpression, Boolean, System.String)'.
  Source=EntityFrameworkCore.UseRowNumberForPaging
  StackTrace:
   at EntityFrameworkCore.UseRowNumberForPaging.SqlServer2008QueryTranslationPostprocessorFactory.SqlServer2008QueryTranslationPostprocessor.Offset2RowNumberConvertVisitor.VisitSelect(SelectExpression selectExpression)
   at EntityFrameworkCore.UseRowNumberForPaging.SqlServer2008QueryTranslationPostprocessorFactory.SqlServer2008QueryTranslationPostprocessor.Offset2RowNumberConvertVisitor.VisitExtension(Expression node)
   at EntityFrameworkCore.UseRowNumberForPaging.SqlServer2008QueryTranslationPostprocessorFactory.SqlServer2008QueryTranslationPostprocessor.Offset2RowNumberConvertVisitor.VisitExtension(Expression node)
   at EntityFrameworkCore.UseRowNumberForPaging.SqlServer2008QueryTranslationPostprocessorFactory.SqlServer2008QueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at DocWeb_Core.Services.StatisticsService.<UpdateStatisticsData>d__12.MoveNext() in C:\Users\XXX\Documents\Visual Studio 2022\Projects\DocWeb Core\DocWeb\Services\StatisticsBackgroundService.cs:line 98

**Comment by yltsa** [comment]
Hi, I fixed this by copying the files into my project and making the following change in SqlServer2008QueryTranslationPostprocessorFactory.cs file. The change is marked by '//XXXIR':

`				private Expression VisitSelect(SelectExpression selectExpression)
				{
					var oldOffset = selectExpression.Offset;
					if (oldOffset == null)
						return selectExpression;

					var oldLimit = selectExpression.Limit;
					var oldOrderings = selectExpression.Orderings;
					//order by in subQuery without TOP N is invalid.
					var newOrderings = oldOrderings.Count > 0 && (oldLimit != null || selectExpression == root)
						? oldOrderings.ToList()
						: new List<OrderingExpression>();
                    selectExpression = selectExpression.Update(selectExpression.Projection.ToList(),
                                                               selectExpression.Tables.ToList(),
                                                               selectExpression.Predicate,
                                                               selectExpression.GroupBy.ToList(),
                                                               selectExpression.Having,
                                                               orderings: newOrderings,
                                                               limit: null,
                                                               offset: null);//XXXIR,
                                                                             //XXXIRselectExpression.IsDistinct,
                                                                             //XXXIRselectExpression.Alias);`

Not sure, if it was good fix. But now the application works with EF7.

**Comment by Rwing** [comment]
Thank you.
This was supported in version 0.4
